### ISSUE TITLE
zsh: parse error near `\n'

### ISSUE THREAD

**Issue by petk** [docksal/get.docksal.io#3] opened 2019-07-09 08:32 UTC
System: Ubuntu 19.04
Shell: zsh 5.5.1 (x86_64-ubuntu-linux-gnu)

When running this: `bash <(curl -fsSL https://get.docksal.io)>` I get the following error:

```
zsh: parse error near `\n'
```

**Comment by lmakarov** [comment] 2019-07-09 10:44
```
ubuntu-s-2vcpu-4gb-fra1-01# bash <(curl -fsSL https://get.docksal.io)>
zsh: parse error near `\n'
```

You have a typo there. Should be: `bash <(curl -fsSL https://get.docksal.io)`

Also, Ubuntu 19.04 is not officially supported by Docker. See:
https://docs.docker.com/install/linux/docker-ce/ubuntu/#os-requirements

The get.docksal.com install (which Docksal relies on) fails on Ubuntu 19.04:

```
ubuntu-s-2vcpu-4gb-fra1-01# bash <(curl -fsSL https://get.docker.com) 
# Executing docker install script, commit: 2f4ae48
+ sh -c 'apt-get update -qq >/dev/null'
+ sh -c 'apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null'
+ sh -c 'curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null'
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable" > /etc/apt/sources.list.d/docker.list'
+ sh -c 'apt-get update -qq >/dev/null'
+ '[' -n '' ']'
+ sh -c 'apt-get install -y -qq --no-install-recommends docker-ce >/dev/null'
E: Package 'docker-ce' has no installation candidate
```

I'm closing this as won't fix, since the issue is upstream and there is not much we can do with it.

**Closed as completed by lmakarov** 2019-07-09 10:44 UTC
Labels: invalid, wontfix

**Comment by petk** [comment] 2019-07-09 10:55
Thank you @lmakarov I'm not sure where I got that character at the end, yes. It goes through without error now, yes. At least to the part where Ubuntu 19.04 becomes the issue. 

It will do... Thanks.

**Comment by petk** [comment] 2019-07-09 12:07
Worth noting that Ubuntu 19.04 seems to be fully supported. Only docker needs to be manually installed at the time of this writing using `curl -fsSL get.docker.com | CHANNEL=test sh` or similar approach. Then fin works flawlessly. At least here :)

**Comment by ozgunteksoy** [comment] 2022-09-20 09:19
System : macMonterey 12.6
I'm bioinformatic student and when I'm writing 
curl / http://hgdownload.cse.ucsc.edu/goldenPath/hg38/chromosomes/chr22.fa.gz / gunzip -c >,
I'm getting a message: zsh: parse error near `\n'
What does it mean and how can I solve it?

**Comment by petk** [comment] 2022-09-20 19:46
@ozgunteksoy, see above. In my case it was additional character (empty new line) pasted at the end of the command. Try writing the command manually without pasting it and see the difference if there's anything pasted there. Happens on macOS often.

**Comment by droidjedininja** [comment] 2023-08-04 23:09
You were right to write it out instead of copy and paste! @petk The error is somewhere from the pasting part or it could be the way the text was copied and then pasted!

**Comment by Arpitxd41** [comment] 2023-10-15 21:34
echo "export NVM_DIR=~/.nvm\nsource \$(brew --prefix nvm)/nvm.sh" >> .zshrc
i am getting same error with this line of code and I don't know what to do.

system: macbook pro
